AWSTemplateFormatVersion: '2010-09-09'
Description: CID Data Collection - Role for Management Account v3.4.1
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Deployment parameters"
        Parameters:
          - DataCollectionAccountID
          - ManagementAccountRole
          - ResourcePrefix
      - Label:
          default: "Available modules"
        Parameters:
          - IncludeBackupModule
          - IncludeComputeOptimizerModule
          - IncludeCostAnomalyModule
          - IncludeSupportCasesModule
          - IncludeHealthEventsModule
          - IncludeRightsizingModule
          - IncludeLicenseManagerModule
          - IncludeServiceQuotasModule
    ParameterLabels:
      ManagementAccountRole:
        default: "Management account role"
      DataCollectionAccountID:
        default: "Data Collection Account Id"
      ResourcePrefix:
        default: "Role Prefix"
      IncludeComputeOptimizerModule:
        default: "Include AWS Compute Optimizer Data Collection Module"
      IncludeCostAnomalyModule:
        default: "Include Cost Anomalies Data Collection Module"
      IncludeSupportCasesModule:
        default: "Include Support Cases Data Collection Module"
      IncludeRightsizingModule:
        default: "Include Rightsizing Recommendations Data Collection Module"
      IncludeBackupModule:
        default: "Include AWS Backup Collection Module"
      IncludeHealthEventsModule:
        default: "Include Health Events Module"
      IncludeLicenseManagerModule:
        default: "Include Marketplace Licensing Module"
      IncludeServiceQuotasModule:
        default: "Include Service Quotas Module"
Parameters:
  DataCollectionAccountID:
    Type: String
    Description: AccountId of where the collector is deployed
  ManagementAccountRole:
    Type: String
    Description: Name of role deployed into Management account to read high level data
    Default: "Lambda-Assume-Role-Management-Account"
  ResourcePrefix:
    Type: String
    Description: This prefix will be placed in front of all roles created. Note you may wish to add a dash at the end to make more readable e.g. prefix-
    Default: "CID-DC-"
  IncludeComputeOptimizerModule:
    Type: String
    Description: Collects AWS Compute Optimizer service recommendations
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeCostAnomalyModule:
    Type: String
    Description: "Collects AWS Cost Explorer Cost Anomalies Recommendations"
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeSupportCasesModule:
    Type: String
    Description: "Collects AWS Support Cases data"
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeRightsizingModule:
    Type: String
    Description: "Collects AWS Cost Explorer Rightsizing Recommendations"
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeBackupModule:
    Type: String
    Description: Collects TransitGateway from your accounts
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeHealthEventsModule:
    Type: String
    Description: Collects AWS Health Events from your accounts
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeLicenseManagerModule:
    Type: String
    Description: Collects Marketplace Licensing Information from your accounts
    AllowedValues: ['yes', 'no']
    Default: 'no'
  IncludeServiceQuotasModule:
    Type: String
    Description: Collects Service Quotas Information from your accounts
    AllowedValues: ['yes', 'no']
    Default: 'no'

Conditions:
  EnableComputeOptimizerModule: !Equals [!Ref IncludeComputeOptimizerModule, "yes"]
  EnableCostAnomaliesModule: !Equals [!Ref IncludeCostAnomalyModule, "yes"]
  EnableSupportCasesModule: !Equals [!Ref IncludeSupportCasesModule, "yes"]
  EnableRightsizingModule: !Equals [!Ref IncludeRightsizingModule, "yes"]
  EnableBackupModule: !Equals [!Ref IncludeBackupModule, "yes"]
  EnableHealthEventsModule: !Equals [!Ref IncludeHealthEventsModule, "yes"]
  EnableLicenseManagerModule: !Equals [!Ref IncludeLicenseManagerModule, "yes"]
  EnableServiceQuotasModule: !Equals [!Ref IncludeServiceQuotasModule, "yes"]

Outputs:
  LambdaRole:
    Description: Role for lambda to assume in cost account
    Value: !GetAtt LambdaRole.Arn
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ResourcePrefix}${ManagementAccountRole}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:root"
            Condition:
              ForAnyValue:ArnEquals:
                aws:PrincipalArn:
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}account-collector-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}organizations-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}compute-optimizer-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}cost-anomaly-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}support-cases-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}support-cases-summarization-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}cost-explorer-rightsizing-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}backup-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}health-events-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}license-manager-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}RLS-LambdaRole"
                  - !Sub "arn:${AWS::Partition}:iam::${DataCollectionAccountID}:role/${ResourcePrefix}service-quotas-LambdaRole"
      Path: /
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Role must have an explicit RoleName for traceability"
          - id: W11
            reason: "Role is intended to describe a range of resources"
  AWSOrganizationPolicy:
    Type: "AWS::IAM::Policy"
    #Condition: IsAnyModuleEnabled
    Properties:
      PolicyName: Management-Account-permissions
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "organizations:ListAccountsForParent"
              - "organizations:DescribeAccount"
              - "organizations:ListParents"
              - "organizations:ListRoots"
              - "organizations:ListChildren"
              - "organizations:ListTagsForResource"
              - "organizations:ListAccounts"
              - "organizations:DescribeOrganizationalUnit"
              - "organizations:ListCreateAccountStatus"
              - "organizations:DescribeOrganization"
              - "organizations:ListOrganizationalUnitsForParent"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  RightsizingRecommendationsPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableRightsizingModule
    Properties:
      PolicyName: RightsizingRecommendationsPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ce:GetRightsizingRecommendation"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  CostAnomaliesPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableCostAnomaliesModule
    Properties:
      PolicyName: CostAnomaliesPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ce:GetAnomalies"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  SupportCasesPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableSupportCasesModule
    Properties:
      PolicyName: SupportCasesPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "support:DescribeCases"
              - "support:DescribeCommunications"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  BackupPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableBackupModule
    Properties:
      PolicyName: BackupEventsPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "backup:DescribeBackupJob"
              - "backup:DescribeCopyJob"
              - "backup:DescribeRestoreJob"
              - "backup:ListBackupJobs"
              - "backup:ListCopyJobs"
              - "backup:ListRestoreJobs"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  COExportRecommendations:
    Type: "AWS::IAM::Policy"
    Condition: EnableComputeOptimizerModule
    Properties:
      PolicyName: ComputeOptimizer-ExportRecommendations
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportLambdaFunctionRecommendations"
              - "compute-optimizer:GetLambdaFunctionRecommendations"
              - "lambda:ListFunctions"
              - "lambda:ListProvisionedConcurrencyConfigs"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportAutoScalingGroupRecommendations"
              - "compute-optimizer:GetAutoScalingGroupRecommendations"
              - "autoscaling:DescribeAutoScalingGroups"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportEBSVolumeRecommendations"
              - "compute-optimizer:GetEBSVolumeRecommendations"
              - "ec2:DescribeVolumes"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportEC2InstanceRecommendations"
              - "compute-optimizer:GetEC2InstanceRecommendations"
              - "ec2:DescribeInstances"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportECSServiceRecommendations"
              - "compute-optimizer:GetECSServiceRecommendations"
              - "compute-optimizer:GetECSServiceRecommendationProjectedMetrics"
              - "ecs:ListServices"
              - "ecs:ListClusters"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportLicenseRecommendations"
              - "compute-optimizer:GetLicenseRecommendations"
              - "ec2:DescribeInstances"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "compute-optimizer:ExportRDSDatabaseRecommendations"
              - "compute-optimizer:GetRDSDatabaseRecommendations"
              - "compute-optimizer:GetRDSDatabaseRecommendationProjectedMetrics"
              - "rds:DescribeDBInstances"
              - "rds:DescribeDBClusters"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  HealthEventsPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableHealthEventsModule
    Properties:
      PolicyName: HealthEventsPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "health:DescribeEventsForOrganization"
              - "health:DescribeEventDetailsForOrganization"
              - "health:DescribeAffectedAccountsForOrganization"
              - "health:DescribeAffectedEntitiesForOrganization"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  LicenseManagerPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableLicenseManagerModule
    Properties:
      PolicyName: LicenseManagerPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "license-manager:ListReceivedGrants"
              - "license-manager:ListReceivedLicenses"
              - "license-manager:ListReceivedGrantsForOrganization"
            Resource: "*"
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"
  ServiceQuotasPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EnableServiceQuotasModule
    Properties:
      PolicyName: ServiceQuotasPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "servicequotas:ListServices"
              - "servicequotas:ListRequestedServiceQuotaChangeHistory"
              - "servicequotas:ListServiceQuotas"
              - "servicequotas:ListAWSDefaultServiceQuotas"
            Resource: "*" ## Policy is used for scanning a wide range of resources. All service quotas in this case. All of them.
      Roles:
        - Ref: LambdaRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: "Policy is used for scanning of a wide range of resources"